version: '3.9'
networks:
   service24:
     driver: bridge

services:
  es01:
    image: registry.dev.pyrobyte.ru/pyrodock/crabbit_backend-es01
    restart: always
    environment:
      - node.name=es01
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    volumes:
      - ./data/elastic:/var/lib/elasticsearch/data
    ports:
      - "9220:9200"
    networks:
      - service24

  nginx:
    build:
      context: ./nginx/
      args:
        http_protocol: ${HTTP_PROTOCOL}
        server_name: ${HOSTNAME}
    restart: always
    environment:
      SERVICE_TAGS: ${TAG}
    links:
      - php
    ports:
      - '${API_HTTP_PORT}:80'
    volumes:
      - ./volumes/backend:/var/www/
      - ./nginx/logs:/var/log/nginx/
      - ./nginx/nginx_main.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - service24

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "${MYSQL_HOST_PORT}:${MYSQL_DOCKER_CONTAINER_PORT}"
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SERVICE_TAGS: ${TAG}
      SERVICE_NAME: mysql
    depends_on:
      - es01
    networks:
      - service24

  redis:
    image: redis:7.2-rc-alpine3.18
    restart: always
    environment:
      SERVICE_TAGS: ${TAG}
    ports:
      - ${REDIS_PORT}:6379
    depends_on:
      - es01
    networks:
      - service24

  php:
    build:
      context: ./php/
    restart: always
    environment:
      SERVICE_TAGS: ${TAG}
    ports:
      - '${PORT_PHP}:9000'
    volumes:
      - ./volumes/backend:/var/www
      - ./php/pool.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/supervisor/conf.d:/etc/supervisor/conf.d
      - ./php/cronlogs/cron.log:/var/log/cron.log
    depends_on:
      - es01
      - mysql
    networks:
      - service24